In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.ones((10,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.ones((10,5)).shape

(10, 5)

In [43]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [44]:
np.ones((3,4,5), dtype = np.float64).strides

(160, 40, 8)

In [45]:
ints = np.ones(10,dtype = np.uint16)

In [46]:
floats = np.ones(10, dtype = np.float32)

In [47]:
np.issubdtype(ints.dtype, np.integer)

True

In [48]:
np.issubdtype(floats.dtype, np.floating)

True

In [49]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [50]:
np.issubdtype(ints.dtype, np.number)

True

In [51]:
arr = np.arange(8)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
b = arr.reshape((4,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [54]:
c = arr.reshape((4,2), order = 'C')
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [55]:
d = arr.reshape((4,2), order ='F')
d

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [60]:
other_arr = np.ones((3,5))
other_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
other_arr.shape

(3, 5)

In [62]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [64]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [65]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [66]:
arr = np.random.randn(2,2)
arr

array([[-0.13078192,  0.41079668],
       [ 0.70591017, -0.67368575]])

In [67]:
arr.repeat(2, axis=0)

array([[-0.13078192,  0.41079668],
       [-0.13078192,  0.41079668],
       [ 0.70591017, -0.67368575],
       [ 0.70591017, -0.67368575]])

In [68]:
arr.repeat([2,3],axis=0)

array([[-0.13078192,  0.41079668],
       [-0.13078192,  0.41079668],
       [ 0.70591017, -0.67368575],
       [ 0.70591017, -0.67368575],
       [ 0.70591017, -0.67368575]])

In [69]:
arr.repeat([2,3],axis=1)

array([[-0.13078192, -0.13078192,  0.41079668,  0.41079668,  0.41079668],
       [ 0.70591017,  0.70591017, -0.67368575, -0.67368575, -0.67368575]])

In [70]:
arr.repeat(2)

array([-0.13078192, -0.13078192,  0.41079668,  0.41079668,  0.70591017,
        0.70591017, -0.67368575, -0.67368575])

In [71]:
np.tile(arr,2)

array([[-0.13078192,  0.41079668, -0.13078192,  0.41079668],
       [ 0.70591017, -0.67368575,  0.70591017, -0.67368575]])

In [72]:
np.tile(arr,(2,1))

array([[-0.13078192,  0.41079668],
       [ 0.70591017, -0.67368575],
       [-0.13078192,  0.41079668],
       [ 0.70591017, -0.67368575]])

In [73]:
arr = np.arange(10)*100

In [74]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [75]:
inds = [7,1,2,6]

In [76]:
arr[inds]

array([700, 100, 200, 600])

In [77]:
arr.take(inds)

array([700, 100, 200, 600])

In [78]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [79]:
arr.put(inds, [40,41,42,43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [80]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [81]:
arr*4

array([ 0,  4,  8, 12, 16])

In [82]:
arr

array([0, 1, 2, 3, 4])